package:
  name: data-exchange
  version: '0.1.19'

source:
  git_url: https://github.com/decarlof/data-exchange.git
  
build:
  number: 0

requirements:
  build:
    - python
    - h5py
    - pyhdf
    - tifffile
    - edffile
    - spefile
    - netcdf4
 
  run:
    - python
    - h5py
    - pyhdf
    - tifffile
    - edffile
    - spefile
    - netcdf4

about:
  home: http://tomogrid.readthedocs.org
  license: BSD
  summary: 'X-ray tomography Data Exchange'

